### ISSUE TITLE
Improve route name conventions 

### ISSUE THREAD

**Issue by nakaz** [andimiya/coffee-warehouse-api#1]
![image](https://cloud.githubusercontent.com/assets/2155125/23440637/3f893c1c-fdc1-11e6-80e3-c997e2f00722.png)

From what I see so far is that all `/coffee` routes have a parseable parameter at the end. 

This is rather confusing as it tells me that i can request `/coffee/1` for a coffee based on an ID.

I can also get a coffee via name with the same exact route like `/coffee/some-coffee-name`.

Also you might run into problems where the route is trying to parse both a number and a string. 

Instead the route should be more explicit. 

`/coffee/{id}` is fine. its a general use case

`/coffee/name/{name}`... we know that this route is to find coffee via name.

`/coffee/location/{location}`... we know that this route is to find coffee via location

and so forth!

**Comment by andimiya** [comment]
Updated the route names!
